const { PATHS } = require("./constants");
const { addDay, subtractDay } = require("./addDay");
const { writeDateToFile } = require("./setDate");

module.exports = {
  getPeriod: require("./getPeriodAndTitle").getPeriod,
  getStamp: require("./getStamp").getStamp,
  PATHS: {
    SK_VARS: PATHS.SK_VARS_PATH,
    RK_SCORES: PATHS.RK_SCORES_PATH,
    KC_SCORES: PATHS.KC_SCORES_PATH,
    GLOBAL_VARS: PATHS.GLOBAL_VARS_PATH,
    LOGS: PATHS.LOGS_PATH,
    TEST_RECORDS: PATHS.TEST_RECORDS_PATH,
    TEST_JSON: PATHS.TEST_JSON_PATH,
  },
  date: {
    current: require("./currentDateValues").getDateValues,
    new: require("./newDate").newDate,
    add: addDay,
    subtract: subtractDay,
    write: writeDateToFile,
    validate: require("./validateDate").validateAndFormatDate,
    checkPeriod: require("./newPeriodCheck").checkDateInfo,
  },
  Date: require("./_date"),
  is: require("./_is"),
  lb: require("./_lb"),
  addPlayerScores: require("./addPlayerScores"),
  addScores: require("./addScores"),
  argCount: require("./argCount"),
  checkEndOfPeriod: require("./checkEndOfPeriod"),
  checkScoresInput: require("./checkScoresInput"),
  checkUserExists: require("./checkUserExists"),
  constants: require("./constants"),
  currentDateValues: require("./currentDateValues"),
  defaultPaths: require("./defaultPaths"),
  determineWinners: require("./determineWinners"),
  errorMessages: require("./errorMessages"),
  formatAndSortScores: require("./formatAndSortScores"),
  formatScoresInput: require("./formatScoresInput"),
  formattedLb: require("./formattedLb"),
  generatePlayerTable: require("./generatePlayerTable"),
  getPlayerScoresArray: require("./getPlayerScoresArray"),
  getScoresArray: require("./getScoresArray"),
  index2: require("./index2"),
  leaderboard: require("./leaderboard"),
  newDate: require("./newDate"),
  newPeriodCheck: require("./newPeriodCheck"),
  playerScoresTable: require("./playerScoresTable"),
  processInput: require("./processInput"),
  readAndParseJson: require("./readAndParseJson"),
  removePlayerScores: require("./removePlayerScores"),
  removeScores: require("./removeScores"),
  sanitizeInput: require("./sanitizeInput"),
  schema: require("./schema"),
  scoresIn: require("./scoresIn"),
  scoresOut: require("./scoresOut"),
  tableConfig: require("./table-config"),
  validateDate: require("./validateDate"),
  validateJson: require("./validateJson"),
  writeStructuredJson: require("./writeStructuredJson"),
};
